version: "3.8"
services:
  mysql-auth:
    image: mysql:8
    container_name: mysql-auth
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
      

  mongo-traffic:
    image: mongo
    container_name: mongo-traffic
    ports:
      - "27017:27017"
