
spring:
  data:
    mongodb:
      uri: mongodb+srv://amiralivillan:UrbanStream@urbanstream.fgi0tnd.mongodb.net/auth
  application:
    name: auth-service
  server:
    port: 8081
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: auth-service
            client-secret: p7sALmcBbxzBfPqj7thuphWtxFSKOi3U
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/urbanstream
            user-name-attribute: preferred_username


